### ISSUE TITLE
TypeError: sequence item 0: expected str instance, int found

### ISSUE THREAD

**Issue by caimingqi** [mmmmimic/diffConvNet#6]
(diffconv)root@ailab-PowerEdge-T640:/home/ailab/diffconvNet#pvthon3 data_prep.py --dataset=toronto3d
Traceback (most recent call last):
  File "data_prep.py", line 104, in <module>
    eval("download %s(data_dir)"%dataset)
  File "<string>", line 1, in <module>
  File "data_prep.py", ine 78, in download_toronto3d
    split Toronto3D(i, data dir=data dir)
  File "data_prep.py", line 7, in split_Toronto3D
    import open3d .ml.torch as ml3d
  File "/root/anaconda3/envs/diffconv/lib/python3.7/site-packages/open3d/ml/torch/ __init__.py", line 38, in<module>
    match_torch_ver = '.'.join( o3d torch version.release[:2] + ('*',))
TypeError: sequence item 0: expected str instance, int found

how to solve the question?

**Comment by mmmmimic** [comment]
Hi, I didn't encounter this error before. But it seems that it failed to load open3d. In 'match_torch_ver = '.'.join( o3d torch version.release[:2] + ('*',))', o3d_torch_version.release[:2] is an integer, which should be a string. You may want to change the type of it by str()? This is an open3D error thus please also check if open3d was installed correctly:)

**Comment by caimingqi** [comment]
can you tell me the required open3d version

**Comment by mmmmimic** [comment]
I am using open3d 0.15.2

**Comment by caimingqi** [comment]
Is this the "processing 63.65％ points in region 2" when running?  It is so slow.

**Comment by mmmmimic** [comment]
Yes, I am afraid it is slow.

**Comment by caimingqi** [comment]
I also encountered problems raised by others during the Scene segmentation，many values remain unchanged，Does it change to change the default super parameter，i may try it

Train 152, loss: 1.704556, train acc: 0.579693, train avg acc: 0.111111, train iou: 0.072462, mean iou: 0.716269
Test 152, loss: 1.720625, test acc: 0.545929, test avg acc: 0.111111, test iou: 0.068241, mean iou: 0.693581
Train 153, loss: 1.699433, train acc: 0.584002, train avg acc: 0.111111, train iou: 0.073000, mean iou: 0.716085
Test 153, loss: 1.721535, test acc: 0.545929, test avg acc: 0.111111, test iou: 0.068241, mean iou: 0.693581
Train 154, loss: 1.701942, train acc: 0.581193, train avg acc: 0.111111, train iou: 0.072649, mean iou: 0.716602
Test 154, loss: 1.719878, test acc: 0.545929, test avg acc: 0.111111, test iou: 0.068241, mean iou: 0.693581
Train 155, loss: 1.699353, train acc: 0.582737, train avg acc: 0.111111, train iou: 0.072842, mean iou: 0.716361
Test 155, loss: 1.722167, test acc: 0.545929, test avg acc: 0.111111, test iou: 0.068241, mean iou: 0.693581

**Comment by mmmmimic** [comment]
Hi, I am sorry for the problem. As you may notice from the other post I failed to reproduce the error when I ran the experiments from scratch and I have no idea about this.

**Comment by mmmmimic** [comment]
Hi, if you are still interested please check issue #7
